In [1]:
! pip install numpy

In [3]:
import numpy as np

## Why  Numpy?

In [4]:
lst = list(range(10))
print(lst)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [5]:
l = [i**2 for i in range(0,10)]
print(l)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [6]:
%timeit [i**2 for i in range(0,10)]

2.36 µs ± 35.8 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [8]:
arr = np.array(lst)

In [10]:
print(arr**2)

[ 0  1  4  9 16 25 36 49 64 81]


In [11]:
%timeit arr**2

441 ns ± 4.61 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [12]:
print(lst)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [13]:
lst*2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [15]:
arr*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

# Numpy Basics

In [17]:
lst = [1,2,3,4,5]

arr = np.array(lst)
arr

array([1, 2, 3, 4, 5])

In [19]:
arr

array([1, 2, 3, 4, 5])

In [20]:
type(arr)

numpy.ndarray

In [21]:
arr.ndim

1

In [22]:
arr.shape

(5,)

In [24]:
arr.size

5

In [26]:
np.arange(2, 15, 2)

array([ 2,  4,  6,  8, 10, 12, 14])

In [27]:
lst = [ [1,2,3], [4,5,6], [7,8,9] ]

In [29]:
arr = np.array(lst)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
arr.shape

(3, 3)

In [31]:
arr.size

9

In [34]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [38]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [48]:
np.diag([1,2,3,4]).astype('float')

array([[1., 0., 0., 0.],
       [0., 2., 0., 0.],
       [0., 0., 3., 0.],
       [0., 0., 0., 4.]])

In [47]:
I = np.identity(3, dtype='uint8')
I 

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=uint8)

In [44]:
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Indexing in Arrays

In [56]:
arr = np.random.randint(10, 100, size=(5,4))

In [57]:
arr

array([[71, 34, 85, 25],
       [96, 41, 35, 73],
       [53, 52, 55, 38],
       [73, 87, 84, 15],
       [23, 51, 73, 56]])

In [58]:
arr.shape

(5, 4)

In [66]:
len(arr)

5

In [67]:
arr[0,0]

71

In [68]:
arr[-1,-1]

56

In [70]:
arr.size

20

## Array slicing

In [71]:
arr

array([[71, 34, 85, 25],
       [96, 41, 35, 73],
       [53, 52, 55, 38],
       [73, 87, 84, 15],
       [23, 51, 73, 56]])

`arr[ rows , cols]`

`arr[ start_row : end_row +1 , start_col : end_col + 1]`

In [72]:
arr[ 2 : 4 , 1 : 3 ]

array([[52, 55],
       [87, 84]])

In [73]:
arr[ 2:4 , : ]

array([[53, 52, 55, 38],
       [73, 87, 84, 15]])

In [75]:
sub_arr = arr[1:4, 2:]
sub_arr

array([[35, 73],
       [55, 38],
       [84, 15]])

In [79]:
arr[1:-1, 2:]

array([[35, 73],
       [55, 38],
       [84, 15]])

In [76]:
# assigning new values

arr[0,0] = 0

In [77]:
arr

array([[ 0, 34, 85, 25],
       [96, 41, 35, 73],
       [53, 52, 55, 38],
       [73, 87, 84, 15],
       [23, 51, 73, 56]])

In [81]:
arr[1:-1, 2:] = 1

In [82]:
arr

array([[ 0, 34, 85, 25],
       [96, 41,  1,  1],
       [53, 52,  1,  1],
       [73, 87,  1,  1],
       [23, 51, 73, 56]])

### boolean masking

In [86]:
bool_mask = arr > 50
bool_mask

array([[False, False,  True, False],
       [ True, False, False, False],
       [ True,  True, False, False],
       [ True,  True, False, False],
       [False,  True,  True,  True]])

In [90]:
bool_mask.sum()

9

In [93]:
arr[bool_mask]

array([85, 96, 53, 52, 73, 87, 51, 73, 56])

In [96]:
arr[ arr>50 ]

array([85, 96, 53, 52, 73, 87, 51, 73, 56])

In [98]:
arr == 1

array([[False, False, False, False],
       [False, False,  True,  True],
       [False, False,  True,  True],
       [False, False,  True,  True],
       [False, False, False, False]])

## Numpy Operations

In [99]:
a = np.array([2,4])
b = np.array([5,2])

In [100]:
a

array([2, 4])

In [101]:
b

array([5, 2])

In [102]:
a+b

array([7, 6])

In [103]:
a-b

array([-3,  2])

In [104]:
a*b

array([10,  8])

In [105]:
a*2

array([4, 8])

In [108]:
np.log2(10)

3.321928094887362

In [109]:
np.log2(a)

array([1., 2.])

In [110]:
np.sin(a)

array([ 0.90929743, -0.7568025 ])

### Matrix Operations

In [128]:
A = np.random.randint(1, 5, size=(3,4))
B = np.random.randint(1, 5, size=(4,5))

In [129]:
A

array([[2, 2, 2, 3],
       [4, 4, 3, 4],
       [2, 1, 3, 1]])

In [130]:
B

array([[4, 3, 2, 4, 4],
       [1, 4, 3, 3, 4],
       [3, 1, 4, 4, 4],
       [1, 3, 1, 3, 1]])

In [131]:
print(A.shape)
print(B.shape)

(3, 4)
(4, 5)


In [132]:
np.dot(A, B)

array([[19, 25, 21, 31, 27],
       [33, 43, 36, 52, 48],
       [19, 16, 20, 26, 25]])

In [133]:
# A@B

array([[19, 25, 21, 31, 27],
       [33, 43, 36, 52, 48],
       [19, 16, 20, 26, 25]])

In [136]:
np.matmul(A, B)

array([[19, 25, 21, 31, 27],
       [33, 43, 36, 52, 48],
       [19, 16, 20, 26, 25]])

## Misc functions

In [138]:
A

array([[2, 2, 2, 3],
       [4, 4, 3, 4],
       [2, 1, 3, 1]])

In [139]:
np.reshape(A, (6, 2))

array([[2, 2],
       [2, 3],
       [4, 4],
       [3, 4],
       [2, 1],
       [3, 1]])

In [146]:
np.reshape(A, (1, 12))

array([[2, 2, 2, 3, 4, 4, 3, 4, 2, 1, 3, 1]])

In [148]:
vec = np.arange(0,16)

In [157]:
np.reshape(vec, (3,4))

ValueError: cannot reshape array of size 16 into shape (3,4)

In [160]:
np.sqrt(B)

array([[2.        , 1.73205081, 1.41421356, 2.        , 2.        ],
       [1.        , 2.        , 1.73205081, 1.73205081, 2.        ],
       [1.73205081, 1.        , 2.        , 2.        , 2.        ],
       [1.        , 1.73205081, 1.        , 1.73205081, 1.        ]])

In [163]:
B

array([[4, 3, 2, 4, 4],
       [1, 4, 3, 3, 4],
       [3, 1, 4, 4, 4],
       [1, 3, 1, 3, 1]])

In [164]:
B.shape

(4, 5)

In [162]:
np.sum(B)

57

In [168]:
# sum across columns
np.sum(B, axis=0)

array([ 9, 11, 10, 14, 13])

In [169]:
# sum across rows
np.sum(B, axis=1)

array([17, 15, 16,  9])

In [171]:
np.mean(B, axis=0)

array([2.25, 2.75, 2.5 , 3.5 , 3.25])

In [173]:
B

array([[4, 3, 2, 4, 4],
       [1, 4, 3, 3, 4],
       [3, 1, 4, 4, 4],
       [1, 3, 1, 3, 1]])

In [174]:
np.transpose(B)

array([[4, 1, 3, 1],
       [3, 4, 1, 3],
       [2, 3, 4, 1],
       [4, 3, 4, 3],
       [4, 4, 4, 1]])

In [178]:
np.arange(4).T

array([0, 1, 2, 3])

### methods
- np.vstack()
- np.hstack()

In [182]:
a = np.arange(2, 6).reshape(2,2)

In [184]:
np.vstack((a,a))

array([[2, 3],
       [4, 5],
       [2, 3],
       [4, 5]])

In [185]:
np.hstack((a,a))

array([[2, 3, 2, 3],
       [4, 5, 4, 5]])

# Broadcasting

In [188]:
A = np.random.randint(1, 10, (3,3))

In [189]:
A

array([[8, 6, 8],
       [1, 1, 4],
       [6, 7, 3]])

In [196]:
a = np.array([[1,2,3]])

In [197]:
A.shape

(3, 3)

In [198]:
a.shape

(1, 3)

In [195]:
A + a

array([[ 9,  8, 11],
       [ 2,  3,  7],
       [ 7,  9,  6]])

In [203]:
a.T

array([[1],
       [2],
       [3]])

In [204]:
A + a.T

array([[ 9,  7,  9],
       [ 3,  3,  6],
       [ 9, 10,  6]])

In [206]:
A*2

array([[16, 12, 16],
       [ 2,  2,  8],
       [12, 14,  6]])

# Vectorization

In [210]:
a = np.array([2,4])
b = np.array([7,1])

In [211]:
d  = 0.0

for i in range(2):
    d += (a[i] -  b[i])**2
    
print(d**0.5)

5.830951894845301


In [215]:
np.sqrt(np.sum((a-b)**2))

5.830951894845301