In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('cars24-car-price.csv')

In [3]:
df.shape

(19980, 11)

In [4]:
df.head()

full_name  selling_price    year  \
0                                 Maruti Alto Std           1.20  2012.0   
1                          Hyundai Grand i10 Asta           5.50  2016.0   
2                                Hyundai i20 Asta           2.15  2010.0   
3                   Maruti Alto K10 2010-2014 VXI           2.26  2012.0   
4  Ford Ecosport 2015-2021 1.5 TDCi Titanium BSIV           5.70  2015.0   

  seller_type  km_driven fuel_type transmission_type  mileage  engine  \
0  Individual     120000    Petrol            Manual    19.70   796.0   
1  Individual      20000    Petrol            Manual    18.90  1197.0   
2  Individual      60000    Petrol            Manual    17.00  1197.0   
3  Individual      37000    Petrol            Manual    20.92   998.0   
4      Dealer      30000    Diesel            Manual    22.77  1498.0   

   max_power  seats  
0      46.30    5.0  
1      82.00    5.0  
2      80.00    5.0  
3      67.10    5.0  
4      98.59    5.0

In [6]:
df.isna().sum()

full_name            0
selling_price        0
year                 0
seller_type          0
km_driven            0
fuel_type            0
transmission_type    0
mileage              0
engine               0
max_power            0
seats                0
dtype: int64

In [16]:
df.drop(columns=['full_name'], inplace=True)

In [17]:
df.head()

selling_price    year seller_type  km_driven fuel_type transmission_type  \
0           1.20  2012.0  Individual     120000    Petrol            Manual   
1           5.50  2016.0  Individual      20000    Petrol            Manual   
2           2.15  2010.0  Individual      60000    Petrol            Manual   
3           2.26  2012.0  Individual      37000    Petrol            Manual   
4           5.70  2015.0      Dealer      30000    Diesel            Manual   

   mileage  engine  max_power  seats  
0    19.70   796.0      46.30    5.0  
1    18.90  1197.0      82.00    5.0  
2    17.00  1197.0      80.00    5.0  
3    20.92   998.0      67.10    5.0  
4    22.77  1498.0      98.59    5.0

In [20]:
cat_vars = list(df.dtypes[(df.dtypes == 'object')].index)
cat_vars

['seller_type', 'fuel_type', 'transmission_type']

In [24]:
df['seller_type'].value_counts()

Dealer              11973
Individual           7817
Trustmark Dealer      190
Name: seller_type, dtype: int64

In [25]:
df['fuel_type'].value_counts()

Diesel      9817
Petrol      9767
CNG          316
LPG           66
Electric      14
Name: fuel_type, dtype: int64

In [26]:
df['transmission_type'].value_counts()

Manual       16029
Automatic     3951
Name: transmission_type, dtype: int64

In [28]:
df['transmission_type'] = df['transmission_type'].astype('category').cat.codes

In [29]:
cat_vars = list(df.dtypes[(df.dtypes == 'object')].index)
cat_vars

['seller_type', 'fuel_type']

In [31]:
df[cat_vars].head()

seller_type fuel_type
0  Individual    Petrol
1  Individual    Petrol
2  Individual    Petrol
3  Individual    Petrol
4      Dealer    Diesel

In [33]:
ohe = pd.get_dummies(df[cat_vars])
ohe.head()

seller_type_Dealer  seller_type_Individual  seller_type_Trustmark Dealer  \
0                   0                       1                             0   
1                   0                       1                             0   
2                   0                       1                             0   
3                   0                       1                             0   
4                   1                       0                             0   

   fuel_type_CNG  fuel_type_Diesel  fuel_type_Electric  fuel_type_LPG  \
0              0                 0                   0              0   
1              0                 0                   0              0   
2              0                 0                   0              0   
3              0                 0                   0              0   
4              0                 1                   0              0   

   fuel_type_Petrol  
0                 1  
1                 1  
2                 1  
3                 1  
4                 0

In [35]:
df = df.drop(columns=cat_vars)

In [37]:
df.head()

selling_price    year  km_driven  transmission_type  mileage  engine  \
0           1.20  2012.0     120000                  1    19.70   796.0   
1           5.50  2016.0      20000                  1    18.90  1197.0   
2           2.15  2010.0      60000                  1    17.00  1197.0   
3           2.26  2012.0      37000                  1    20.92   998.0   
4           5.70  2015.0      30000                  1    22.77  1498.0   

   max_power  seats  
0      46.30    5.0  
1      82.00    5.0  
2      80.00    5.0  
3      67.10    5.0  
4      98.59    5.0

In [40]:
df = pd.concat((df,ohe), axis=1)

In [42]:
df.shape

(19980, 16)

In [41]:
df.head()

selling_price    year  km_driven  transmission_type  mileage  engine  \
0           1.20  2012.0     120000                  1    19.70   796.0   
1           5.50  2016.0      20000                  1    18.90  1197.0   
2           2.15  2010.0      60000                  1    17.00  1197.0   
3           2.26  2012.0      37000                  1    20.92   998.0   
4           5.70  2015.0      30000                  1    22.77  1498.0   

   max_power  seats  seller_type_Dealer  seller_type_Individual  \
0      46.30    5.0                   0                       1   
1      82.00    5.0                   0                       1   
2      80.00    5.0                   0                       1   
3      67.10    5.0                   0                       1   
4      98.59    5.0                   1                       0   

   seller_type_Trustmark Dealer  fuel_type_CNG  fuel_type_Diesel  \
0                             0              0                 0   
1                             0              0                 0   
2                             0              0                 0   
3                             0              0                 0   
4                             0              0                 1   

   fuel_type_Electric  fuel_type_LPG  fuel_type_Petrol  
0                   0              0                 1  
1                   0              0                 1  
2                   0              0                 1  
3                   0              0                 1  
4                   0              0                 0

In [43]:
Y = df['selling_price'].values
X = df.drop(columns=['selling_price']).values

In [44]:
X.shape

(19980, 15)

In [46]:
Y = Y.reshape(-1, 1)
Y.shape

(19980, 1)

In [49]:
from sklearn.linear_model import LinearRegression

In [50]:
model_lr =  LinearRegression()

In [51]:
model_lr  = model_lr.fit(X, Y)

In [54]:
model_lr.coef_

array([[ 5.91807521e-01, -1.01437437e-05, -2.32099777e+00,
        -5.42557364e-02,  2.96329704e-03,  1.04867717e-01,
        -9.55473961e-01,  2.70864256e-01,  3.03220049e-01,
        -5.74084305e-01, -1.22352164e-01, -1.45297204e+00,
         2.55244769e+00,  1.25543217e+00, -2.23255567e+00]])

In [55]:
model_lr.intercept_

array([-1189.34621761])

In [58]:
X[100].shape

(15,)

In [60]:
model_lr.predict(X[100].reshape(1, -1))

array([[4.1777918]])

In [61]:
Y[100]

array([4.5])

# evaluate?

In [62]:
model_lr.score(X, Y)

0.6003938638569908